name: CI — Fraud Detection Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install ruff
        run: pip install ruff
      - name: Lint src/
        run: ruff check src/ --ignore E501,F401,E402

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Java
        run: |
          sudo apt-get update -q
          sudo apt-get install -y openjdk-11-jdk
          echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install pyspark==3.5.0 delta-spark==3.0.0 pytest==7.4.4 pytest-cov==4.1.0 PyYAML==6.0.1

      - name: Set PYSPARK_PYTHON
        run: echo "PYSPARK_PYTHON=$(which python)" >> $GITHUB_ENV

      - name: Run unit tests
        run: |
          pytest tests/unit/ -v \
            --cov=src/bronze_to_silver \
            --cov=src/silver_to_gold \
            --cov-report=term-missing \
            --cov-fail-under=30